### ISSUE TITLE
you need to change option_list

### ISSUE THREAD

**Issue by paragkulkarni** [stbarnabas/django-icybackup#11]
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/vhosts/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/www/vhosts/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/vhosts/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/var/www/vhosts/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/vhosts/env/local/lib/python2.7/site-packages/icybackup/management/commands/backup.py", line 13, in <module>
    class Command(BaseCommand):
  File "/var/www/vhosts/env/local/lib/python2.7/site-packages/icybackup/management/commands/backup.py", line 14, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'

And  django.core.management.base.BaseCommand is not containing option_list

**Comment by daisylb** [comment]
Hi,

Thank you for your contribution!

Unfortunately, this project is no longer actively maintained, and I will be archiving it soon.
